import type { CharId } from '@banpick/types'

import manifest from './generated/art.json' with { type: 'json' }

/**
 * Character portraits.
 *
 * **Art is optional, everywhere.** Every component that shows a character falls back to initials
 * when there is no image, and nothing about the game depends on one existing. That is not
 * defensive coding for its own sake — it is what makes deleting `apps/web/public/art/` a
 * complete and supported way to remove the licensed imagery, which the app is designed to
 * survive rather than break under.
 *
 * The manifest is generated by `scripts/fetch-hero-art.mjs` from the publisher's hero index.
 * Heroes with no card there — currently Deadpool — simply have no entry.
 */
const ART = manifest as Record<string, string>

export function artFor(id: CharId): string | null {
  return ART[id] ?? null
}

export function hasArt(id: CharId): boolean {
  return id in ART
}

/**
 * Initials for the fallback tile.
 *
 * Two letters from two words ("Moon Elf" -> ME), otherwise the first two ("Thor" -> TH), which
 * keeps every tile the same visual weight whether or not it has a picture.
 */
export function initialsOf(name: string): string {
  const words = name
    .replace(/[^\p{L}\s]/gu, '')
    .trim()
    .split(/\s+/)
  if (words.length >= 2) return (words[0]![0]! + words[1]![0]!).toUpperCase()
  return (words[0] ?? '?').slice(0, 2).toUpperCase()
}

/**
 * A deterministic hue per character, so a fallback tile is still recognisable at a glance and
 * two adjacent ones do not look identical. Derived from the id, so it never changes.
 */
export function hueFor(id: CharId): number {
  let h = 0
  for (let i = 0; i < id.length; i++) h = (h * 31 + id.charCodeAt(i)) % 360
  return h
}
